#!/usr/bin/env ruby

def system!(*args)
  puts "+ #{args.join(' ')}"
  system(*args) || abort("\n== Command #{args} failed ==")
end

Dir.glob('spec/fixtures/*.yaml').each do |path|
  path.delete_suffix!('.yaml')
  system! "tomograph \"#{path}.yaml\" \"#{path}.json\""
end
